// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaPZ2IKfNSFRzTG3w2rZ8IJjc4l2JWoQ',
    appId: '1:632592536519:web:ce585a2aafab64be4c3fe2',
    messagingSenderId: '632592536519',
    projectId: 'locafy-ab51c',
    authDomain: 'locafy-ab51c.firebaseapp.com',
    storageBucket: 'locafy-ab51c.firebasestorage.app',
    measurementId: 'G-PMK5STQ2DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgxNsPqtdOYXr9SPusz9AXrCwA2B_W4J8',
    appId: '1:632592536519:android:bd0c518c2d2e0a904c3fe2',
    messagingSenderId: '632592536519',
    projectId: 'locafy-ab51c',
    storageBucket: 'locafy-ab51c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmYVbI8JkDNIqqSPtjjwm3JTeWjiS96sU',
    appId: '1:632592536519:ios:6521fe07cdccb0084c3fe2',
    messagingSenderId: '632592536519',
    projectId: 'locafy-ab51c',
    storageBucket: 'locafy-ab51c.firebasestorage.app',
    androidClientId: '632592536519-gud5lmqqevedup50f1pva70u65q477uj.apps.googleusercontent.com',
    iosClientId: '632592536519-pqlfhf3oepkp6008fehkpkqv264t6sc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.locafy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmYVbI8JkDNIqqSPtjjwm3JTeWjiS96sU',
    appId: '1:632592536519:ios:6521fe07cdccb0084c3fe2',
    messagingSenderId: '632592536519',
    projectId: 'locafy-ab51c',
    storageBucket: 'locafy-ab51c.firebasestorage.app',
    androidClientId: '632592536519-gud5lmqqevedup50f1pva70u65q477uj.apps.googleusercontent.com',
    iosClientId: '632592536519-pqlfhf3oepkp6008fehkpkqv264t6sc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.locafy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByaPZ2IKfNSFRzTG3w2rZ8IJjc4l2JWoQ',
    appId: '1:632592536519:web:9dfe308053e801414c3fe2',
    messagingSenderId: '632592536519',
    projectId: 'locafy-ab51c',
    authDomain: 'locafy-ab51c.firebaseapp.com',
    storageBucket: 'locafy-ab51c.firebasestorage.app',
    measurementId: 'G-SWEBWPHRMZ',
  );
}
